CREATE TABLE IF NOT EXISTS accounts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    account VARCHAR(255) NOT NULL UNIQUE KEY,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS req_statuses (
    id INT PRIMARY KEY AUTO_INCREMENT,
    req_status INT NOT NULL UNIQUE KEY,
);

CREATE TABLE IF NOT EXISTS appd_statuses (
    id INT PRIMARY KEY AUTO_INCREMENT,
    appd_status INT NOT NULL UNIQUE KEY,
);

CREATE TABLE IF NOT EXISTS cars (
    id INT PRIMARY KEY AUTO_INCREMENT,
    car_number VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL,     /* FK */
    place VARCHAR(255) NOT NULL,     /* FK */
    insurance TEXT NOT NULL,
    inspection TEXT NOT NULL,
    remarks TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    CONSTRAINT fk_owner
    FOREIGN KEY (owner)
        REFERENCES owners(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
    CONSTRAINT fk_place
    FOREIGN KEY (place)
        REFERENCES places(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS requests (
    id INT PRIMARY KEY AUTO_INCREMENT,
    req_status INT NOT NULL,     /* FK */
    usage_date DATE NOT NULL,
    usage_time TIME NOT NULL,
    car_id INT NOT NULL,     /* FK */
    user VARCHAR(255) NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    manager VARCHAR(255) NOT NULL,
    appd_status INT NOT NULL,     /* FK */
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_req_status
    FOREIGN KEY (req_status)
        REFERENCES req_statuses(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
    CONSTRAINT fk_appd_status
    FOREIGN KEY (appd_status)
        REFERENCES appd_statuses(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
    CONSTRAINT fk_car_id
    FOREIGN KEY (car_id)
        REFERENCES cars(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS owners (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE KEY,
    name VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS places (
    id INT PRIMARY KEY AUTO_INCREMENT,
    place VARCHAR(255) NOT NULL UNIQUE KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
